-- ALTER TABLE IF EXISTS public.auto_parts
--     ADD COLUMN car_autopart_id bigint NOT NULL;
-- ALTER TABLE IF EXISTS public.auto_parts
--     ADD FOREIGN KEY (car_autopart_id)
--         REFERENCES public.cars (autopart_id) MATCH SIMPLE
--     ON
-- UPDATE NO ACTION
-- ON
-- DELETE NO ACTION
--     NOT VALID;